Base ::= SEQUENCE {
    id                      INTEGER,
    serviceTicket           GeneralString,
    requestUuid             GeneralString,
    echo                    GeneralString,
    loggedInUserFromTicket  User
}

User ::= SEQUENCE {
    id                      INTEGER,
    username                [1] EXPLICIT UTF8String OPTIONAL
}

Error ::= SEQUENCE {
    id                      INTEGER,
    serviceTicket           GeneralString,
    requestUuid             GeneralString,
    echo                    GeneralString,
    loggedInUserFromTicket  User,
    errorCode               INTEGER,
    errorMessage            UTF8String
}

Table ::= SEQUENCE {
    tableRecords            [1] EXPLICIT SEQUENCE OF Form OPTIONAL
}

MultipleChoice ::= SEQUENCE {
    selectedRecords         [0] SEQUENCE OF INTEGER
}

Field ::= SEQUENCE {
    id                      INTEGER,
    fieldName               [1] EXPLICIT GeneralString OPTIONAL,
    fieldValText            [2] EXPLICIT UTF8String OPTIONAL,
    fieldValBoolean         [3] EXPLICIT ASN1Boolean OPTIONAL,
    fieldValParagraphText   [4] EXPLICIT UTF8String OPTIONAL,
    fieldValMultiChoice     [5] EXPLICIT MultipleChoice OPTIONAL,
    fieldValDateTime        [6] EXPLICIT GeneralizedTime OPTIONAL,
    fieldValDecimalInt      [7] EXPLICIT INTEGER OPTIONAL,
    fieldValDecimalReal     [8] EXPLICIT GeneralString OPTIONAL,
    fieldValTable           [9] EXPLICIT Table OPTIONAL,
    fieldValEncrypted       [10] EXPLICIT UTF8String OPTIONAL,
    fieldValLabel           [11] EXPLICIT UTF8String OPTIONAL
}

Form ::= SEQUENCE {
    id                      INTEGER,
    serviceTicket           GeneralString,
    requestUuid             GeneralString,
    echo                    GeneralString,
    loggedInUserFromTicket  User,
    formType                [5] EXPLICIT UTF8String OPTIONAL,
    formTypeId              [6] EXPLICIT INTEGER OPTIONAL,
    title                   [7] EXPLICIT UTF8String OPTIONAL,
    flowState               [8] EXPLICIT GeneralString OPTIONAL,
    state                   [9] EXPLICIT GeneralString OPTIONAL,
    currentUser             [10] EXPLICIT User OPTIONAL,
    dateCreated             [11] EXPLICIT GeneralizedTime OPTIONAL,
    dateLastUpdated         [12] EXPLICIT GeneralizedTime OPTIONAL,
    formFields              [13] EXPLICIT SEQUENCE OF Field OPTIONAL
}
